name: HeadsUp
options:
  bundleIdPrefix: com.dpeck
  deploymentTarget:
    macOS: "13.0"
  xcodeVersion: "16.0"
targets:
  HeadsUp:
    type: application
    platform: macOS
    sources:
      - HeadsUp
    settings:
      base:
        INFOPLIST_FILE: HeadsUp/App/Info.plist
        CODE_SIGN_ENTITLEMENTS: HeadsUp/HeadsUp.entitlements
        PRODUCT_BUNDLE_IDENTIFIER: com.dnnypck.HeadsUp
        PRODUCT_NAME: Heads Up
        MARKETING_VERSION: "1.0.2"
        CURRENT_PROJECT_VERSION: "4"
        SWIFT_VERSION: "5.9"
        CODE_SIGN_IDENTITY: "-"
        CODE_SIGN_STYLE: Manual
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        GENERATE_INFOPLIST_FILE: NO
        ENABLE_HARDENED_RUNTIME: YES
    entitlements:
      path: HeadsUp/HeadsUp.entitlements
